### PR TITLE
New forestry logo, equal vertical padding when there is no copy

### PR DESCRIPTION
**Pull request by itsnwa**

### CODE REVIEW

**Comment by itsnwa** [comment]
@budparr Please review my code for bottom padding. The logo wasn't centered when there was no copy below.

**Comment by budparr** [comment]
Yeah, I was just thinking if there's a better way to do that. By the way, you can drop about 1/4 of the file size by optimizing that SVG file: https://jakearchibald.github.io/svgomg/

**Comment by itsnwa** [comment]
woops.. sorry - I usually have that process automated.. It's optimized now.

**Comment by budparr** [comment]
Thank you. Give me just a bit but I should be able to handle this today

**Comment by itsnwa** [comment]
Great, thank you!

**Pull request merged**
